DROP TABLE usuario;
------------ Tablas
CREATE TABLE usuario (
    id_User NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    userPassword VARCHAR(20),
    userName VARCHAR(20),
    nombre VARCHAR2(15),
    apellido VARCHAR2(15),
    correo VARCHAR2(35),
    telefono VARCHAR(15),
    CONSTRAINT user_pk PRIMARY KEY (id_User)
);

CREATE TABLE restaurante (
    id_Restaurante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(20),
    tipo_Comida VARCHAR2(25),
    price_Range NUMBER(1),
    fileName VARCHAR2(500),
    CONSTRAINT restaurante_pk PRIMARY KEY (id_Restaurante)
);

CREATE TABLE platillo (
    id_Platillo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    restaurante NUMBER(25),
    descripcion VARCHAR2(50),
    nombre VARCHAR2(20),
    precio NUMBER(10),
    CONSTRAINT platillo_pk PRIMARY KEY (id_Platillo),
    CONSTRAINT fk_platillo
    FOREIGN KEY (restaurante)
    REFERENCES restaurante(id_Restaurante)
);

CREATE TABLE bebida (
    id_Bebida NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    restaurante NUMBER(25),
    descripcion VARCHAR2(50),
    nombre VARCHAR2(20),
    precio NUMBER(10),
    CONSTRAINT bebida_pk PRIMARY KEY (id_Bebida),
    CONSTRAINT fk_bebida
    FOREIGN KEY (restaurante)
    REFERENCES restaurante(id_Restaurante)
);

CREATE TABLE dieta (
    restaurante NUMBER(25),
    dieta VARCHAR2(50),
    ubicacion VARCHAR2(20),
    CONSTRAINT fk_dieta
    FOREIGN KEY (restaurante)
    REFERENCES restaurante(id_Restaurante)
);

CREATE TABLE empleado (
    id_Empleado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    restaurante NUMBER(25),
    nombre VARCHAR2(15),
    apellido VARCHAR2(15),
    puesto VARCHAR2(20),
    CONSTRAINT empleado_pk PRIMARY KEY (id_Empleado),
    CONSTRAINT fk_empleado
    FOREIGN KEY (restaurante)
    REFERENCES restaurante(id_Restaurante)
);

-- inserts

insert into restaurante(nombre,tipo_Comida, price_Range, fileName)
  values('McDonalds','Fast food', 3, ' ');
  insert into restaurante(nombre,tipo_Comida, price_Range, fileName)
  values('Nacion sushi','asiatico', 5, ' ');
  insert into restaurante(nombre,tipo_Comida, price_Range, fileName)
  values('smash burger','Fast food', 4, ' ');

  select * from restaurante;

  insert into platillo(restaurante,descripcion, nombre, precio)
  values(01,'hamburguesa con queso carne y lechuga', 'quesoburguesa', 2000);
  insert into platillo(restaurante,descripcion, nombre, precio)
  values(02,'arroz japones con salmon camaron y aguacate', 'sushita roll', 7200);
  insert into platillo(restaurante,descripcion, nombre, precio)
  values(01,'hamburguesa con queso carne lechuga con salsa bic mac especial', 'bigmac',3000);
  insert into platillo(restaurante,descripcion, nombre, precio)
  values(01,'pollo', 'pieza de pollo', 1200);
  insert into platillo(restaurante,descripcion, nombre, precio)
  values(03,'hamburguesa con trufa y carne angus', 'truffle hongos burger', 7000);
  insert into platillo(restaurante,descripcion, nombre, precio)
  values(03,'hamburguesa con aguacate y carne angus', 'doble guacamoles', 6500);

  insert into bebida(restaurante,descripcion, nombre, precio)
  values(01,'coca cola', 'coca cola', 1200);
  insert into bebida(restaurante,descripcion, nombre, precio)
  values(02,'vino con frutas','sangria', 2000);
  insert into bebida(restaurante,descripcion, nombre, precio)
  values(03,'bebida de manzana', 'jugo de manzana',700);

  insert into dieta(restaurante,dieta, ubicacion)
    values(01,'vegetariano','san jose');
  insert into dieta(restaurante,dieta, ubicacion)
    values(02,'pescetarian','pinares');
  insert into dieta(restaurante,dieta, ubicacion)
    values(03,'keto', 'curridabat');

    insert into empleado(restaurante,nombre, apellido, puesto)
      values(01,'luis','perez', 'gerente');
    insert into empleado(restaurante,nombre, apellido, puesto)
      values(01,'Ana','Gonzalez', 'cajera');
    insert into empleado(restaurante,nombre, apellido, puesto)
      values(02,'Daniela','Granados', 'mesera');
            

select * from restaurante
   inner join platillo
   on restaurante.id_restaurante = platillo.restaurante
   where id_restaurante = 01;


  -- aqui hay un fuckie fuckie no revisa si ya esta en la tabla

CREATE TABLE review (
    id_Review NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    restaurante VARCHAR2(25),
    usuario VARCHAR2(25),
    rest_score NUMBER(1),
    review VARCHAR2(1024),
    created DATE,
    edited DATE,
    ubicacion VARCHAR2(20),
    fileName VARCHAR2(500),
    CONSTRAINT review_pk PRIMARY KEY (id_Review),
    CONSTRAINT fk_review
    FOREIGN KEY (restaurante), (usuario),(ubicacion)
    REFERENCES restaurante(id_Restaurante, rest_Score), usuario(id_User), ubicacion(id_Ubicacion)
);

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

INSERT INTO review (restaurante, usuario, rating, review, created, ubicacion)
    VALUES ('McDonalds', 'Gabriel', 5, 'Aquí va muchísimo texto', '2022-07-30', 'San José', 'empanada.png');


SELECT * FROM review;

CREATE OR REPLACE PROCEDURE insertReview(
    in_restaurante IN review.restaurante%TYPE,
    in_usuario IN review.usuario%TYPE,
    in_rating IN review.rating%TYPE,
    in_review IN review.review%TYPE,
    in_created IN review.created%TYPE,
    in_ubicacion IN review.ubicacion%TYPE,
    in_fileName IN review.fileName%TYPE)
IS
BEGIN
    INSERT INTO review (restaurante, usuario, rating, review, created, ubicacion, fileName)
    VALUES (in_restaurante, in_usuario, in_rating, in_review, in_created, in_ubicacion, in_fileName);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Review created');
END;

CREATE OR REPLACE PROCEDURE editReview(
    in_idRev IN review.id_Review%TYPE,
    in_rating IN review.rating%TYPE,
    in_review IN review.review%TYPE,
    in_edited IN review.edited%TYPE)
IS
BEGIN
    UPDATE REVIEW SET
        rating = in_rating,
        review = in_review,
        edited = in_edited
    WHERE id_Review = in_idRev;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Review edited');

END;

------------ Agregar un usuario
CREATE OR REPLACE PROCEDURE addUser(
    in_nombre IN usuario.nombre%TYPE,
    in_userPassword IN usuario.userPassword%TYPE,
    in_userName IN usuario.userName%TYPE,
    in_apellido IN usuario.apellido%TYPE,
    in_correo IN usuario.correo%TYPE,
    in_telefono IN usuario.telefono%TYPE)
IS
BEGIN
    INSERT INTO usuario (nombre, userName, userPassword, apellido, correo, telefono)
    VALUES (in_nombre, in_userName, in_userPassword, in_apellido, in_correo, in_telefono);
    COMMIT;
        DBMS_OUTPUT.PUT_LINE('User created');
END;

------------ Eliminar un usuario
CREATE OR REPLACE PROCEDURE deleteUser (
    p_userName in usuario.userName%TYPE,
    p_userPassword IN usuario.userPassword%TYPE)
IS
Begin
    Delete from USUARIO WHERE userName = p_userName and userPassword = p_userPassword ;
    COMMIT;
        DBMS_OUTPUT.PUT_LINE('User deleted');
END;

------------ Editar un usuario
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE alterUser (
    ind_userName IN usuario.userName%TYPE,
    ind_userPassword IN usuario.userPassword%TYPE,
    in_userName IN usuario.userName%TYPE,
    in_nombre IN usuario.nombre%TYPE,
    in_userPassword IN usuario.userPassword%TYPE,
    in_apellido IN usuario.apellido%TYPE,
    in_correo IN usuario.correo%TYPE,
    in_telefono IN usuario.telefono%TYPE)
IS
BEGIN

    UPDATE USUARIO SET
        username = in_userName,
        userpassword = in_userPassword,
        nombre = in_nombre,
        apellido = in_apellido,
        correo = in_correo,
        telefono = in_telefono
    WHERE userName = ind_userName AND userpassword = ind_userPassword;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('User updated');
END;
