--------------------------------------------------------
--  File created - Monday-August-22-2022
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence EMPLEADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VSCODE"."EMPLEADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 100 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RESTAURANTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VSCODE"."RESTAURANTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VSCODE"."USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BEBIDA
--------------------------------------------------------

  CREATE TABLE "VSCODE"."BEBIDA"
   (	"ID_BEBIDA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"RESTAURANTE" NUMBER(25,0),
	"DESCRIPCION" VARCHAR2(500 BYTE),
	"NOMBRE" VARCHAR2(50 BYTE),
	"PRECIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIETA
--------------------------------------------------------

  CREATE TABLE "VSCODE"."DIETA"
   (	"RESTAURANTE" NUMBER(25,0),
	"DIETA" VARCHAR2(50 BYTE),
	"UBICACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "VSCODE"."EMPLEADO"
   (	"ID_EMPLEADO" NUMBER(10,0),
	"RESTAURANTE" NUMBER(25,0),
	"NOMBRE" VARCHAR2(15 BYTE),
	"APELLIDO" VARCHAR2(15 BYTE),
	"PUESTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLATILLO
--------------------------------------------------------

  CREATE TABLE "VSCODE"."PLATILLO"
   (	"ID_PLATILLO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"RESTAURANTE" NUMBER(25,0),
	"DESCRIPCION" VARCHAR2(500 BYTE),
	"NOMBRE" VARCHAR2(50 BYTE),
	"PRECIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE
--------------------------------------------------------

  CREATE TABLE "VSCODE"."RESTAURANTE"
   (	"ID_RESTAURANTE" NUMBER(10,0),
	"NOMBRE" VARCHAR2(20 BYTE),
	"TIPO_COMIDA" VARCHAR2(25 BYTE),
	"PRICE_RANGE" NUMBER(1,0),
	"FILENAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "VSCODE"."REVIEW"
   (	"ID_REVIEW" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"RESTAURANTE" VARCHAR2(25 BYTE),
	"USUARIO" VARCHAR2(25 BYTE),
	"REST_SCORE" NUMBER(1,0),
	"REVIEW" VARCHAR2(1024 BYTE),
	"CREATED" DATE,
	"EDITED" DATE,
	"UBICACION" VARCHAR2(20 BYTE),
	"FILENAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "VSCODE"."USUARIO"
   (	"ID_USER" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"USERPASSWORD" VARCHAR2(20 BYTE),
	"USERNAME" VARCHAR2(20 BYTE),
	"NOMBRE" VARCHAR2(15 BYTE),
	"APELLIDO" VARCHAR2(15 BYTE),
	"CORREO" VARCHAR2(35 BYTE),
	"TELEFONO" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View RESTAURANTE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VSCODE"."RESTAURANTE_VIEW" ("ID_RESTAURANTE", "NOMBRE", "TIPO_COMIDA", "PRICE_RANGE", "FILENAME") AS
  select "ID_RESTAURANTE","NOMBRE","TIPO_COMIDA","PRICE_RANGE","FILENAME"
        from restaurante
       where id_restaurante = restaurantes.get_restaurante
;
REM INSERTING into VSCODE.BEBIDA
SET DEFINE OFF;
Insert into VSCODE.BEBIDA (ID_BEBIDA,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (1,1,'Plain Coca cola','Coca cola',1200);
Insert into VSCODE.BEBIDA (ID_BEBIDA,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (2,2,'Wine and some fruits','Sangr�a',2000);
Insert into VSCODE.BEBIDA (ID_BEBIDA,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (3,3,'Plain apple juice','Apple Juice',700);
Insert into VSCODE.BEBIDA (ID_BEBIDA,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (4,4,'Shot of espresso, Shot of vodka, shot of Licor 43','Espresso Martini',4363);
Insert into VSCODE.BEBIDA (ID_BEBIDA,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (5,4,'Good ol bourbon, Angostura bitters, sugar and orange oils','Old Fashioned',4363);
Insert into VSCODE.BEBIDA (ID_BEBIDA,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (6,4,'Tomato juice, vodka, lemon and lots of hot sauce','Bloody Mary',4363);
REM INSERTING into VSCODE.DIETA
SET DEFINE OFF;
Insert into VSCODE.DIETA (RESTAURANTE,DIETA,UBICACION) values (1,'vegetariano','san jose');
Insert into VSCODE.DIETA (RESTAURANTE,DIETA,UBICACION) values (2,'pescetarian','pinares');
Insert into VSCODE.DIETA (RESTAURANTE,DIETA,UBICACION) values (3,'keto','curridabat');
REM INSERTING into VSCODE.EMPLEADO
SET DEFINE OFF;
Insert into VSCODE.EMPLEADO (ID_EMPLEADO,RESTAURANTE,NOMBRE,APELLIDO,PUESTO) values (101,1,'luis','perez','gerente');
Insert into VSCODE.EMPLEADO (ID_EMPLEADO,RESTAURANTE,NOMBRE,APELLIDO,PUESTO) values (102,1,'Ana','Gonzalez','cajera');
Insert into VSCODE.EMPLEADO (ID_EMPLEADO,RESTAURANTE,NOMBRE,APELLIDO,PUESTO) values (103,2,'Daniela','Granados','mesera');
REM INSERTING into VSCODE.PLATILLO
SET DEFINE OFF;
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (14,1,'Meat, lettuce and cheese burger','CheeseBurger',2000);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (15,2,'Uruchimai with salmon, shrimp and avocado','Sushita roll',7200);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (16,1,'Meat, lettuce and cheese burger with special BigMac sauce','BigMac',3000);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (17,1,'A literal piece of deep fried chicken','Fried Chicken',1200);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (18,3,'Truffle burger with Angus meat','Truffle Hongos Burger',7000);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (19,3,'Angus meat burger with avocado','Doble guacamoles',6500);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (23,4,'Casserole with fried eggs, jalape�os and tomato sauce','Huevos Rancheros',5948);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (24,4,'Homemade bread, maple syrup and fruits','French Toast',3465);
Insert into VSCODE.PLATILLO (ID_PLATILLO,RESTAURANTE,DESCRIPCION,NOMBRE,PRECIO) values (25,4,'Simmered, red wine sauce','Onion Soup',4873);
REM INSERTING into VSCODE.RESTAURANTE
SET DEFINE OFF;
Insert into VSCODE.RESTAURANTE (ID_RESTAURANTE,NOMBRE,TIPO_COMIDA,PRICE_RANGE,FILENAME) values (1,'McDonalds','Fast food',3,' ');
Insert into VSCODE.RESTAURANTE (ID_RESTAURANTE,NOMBRE,TIPO_COMIDA,PRICE_RANGE,FILENAME) values (2,'Nacion sushi','Asian',5,' ');
Insert into VSCODE.RESTAURANTE (ID_RESTAURANTE,NOMBRE,TIPO_COMIDA,PRICE_RANGE,FILENAME) values (3,'smash burger','Fast food',4,' ');
Insert into VSCODE.RESTAURANTE (ID_RESTAURANTE,NOMBRE,TIPO_COMIDA,PRICE_RANGE,FILENAME) values (4,'Garden Bistro','Bistr�',4,' ');
REM INSERTING into VSCODE.REVIEW
SET DEFINE OFF;
Insert into VSCODE.REVIEW (ID_REVIEW,RESTAURANTE,USUARIO,REST_SCORE,REVIEW,CREATED,EDITED,UBICACION,FILENAME) values (17,'PizzaHut','Gandalf',5,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letra',to_date('22-AUG-22','DD-MON-RR'),null,'Tib�s','pizzahut.jpeg');
Insert into VSCODE.REVIEW (ID_REVIEW,RESTAURANTE,USUARIO,REST_SCORE,REVIEW,CREATED,EDITED,UBICACION,FILENAME) values (19,'KFC','Gandalf',4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letra',to_date('22-AUG-22','DD-MON-RR'),null,'Tib�s','kfc.jpeg');
Insert into VSCODE.REVIEW (ID_REVIEW,RESTAURANTE,USUARIO,REST_SCORE,REVIEW,CREATED,EDITED,UBICACION,FILENAME) values (18,'McDonald&#39s','Gandalf',1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',to_date('22-AUG-22','DD-MON-RR'),to_date('22-AUG-22','DD-MON-RR'),'Tib�s','mcdonalds.jpeg');
Insert into VSCODE.REVIEW (ID_REVIEW,RESTAURANTE,USUARIO,REST_SCORE,REVIEW,CREATED,EDITED,UBICACION,FILENAME) values (20,'Garden Bistro','Gandalf',4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letra',to_date('22-AUG-22','DD-MON-RR'),null,'Barrio Escalante','IMG_8500-1-scaled.jpg');
Insert into VSCODE.REVIEW (ID_REVIEW,RESTAURANTE,USUARIO,REST_SCORE,REVIEW,CREATED,EDITED,UBICACION,FILENAME) values (21,'El Mosaico','Gandalf',4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letra',to_date('22-AUG-22','DD-MON-RR'),null,'Barrio Escalante','195748875_4058804527569054_6406027412851154824_n-819x1024.webp');
Insert into VSCODE.REVIEW (ID_REVIEW,RESTAURANTE,USUARIO,REST_SCORE,REVIEW,CREATED,EDITED,UBICACION,FILENAME) values (22,'Tacos Max','Gandalf',5,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

10/10 Empanadas Arregladas',to_date('22-AUG-22','DD-MON-RR'),null,'Zapote','tacos.jpeg');
REM INSERTING into VSCODE.USUARIO
SET DEFINE OFF;
Insert into VSCODE.USUARIO (ID_USER,USERPASSWORD,USERNAME,NOMBRE,APELLIDO,CORREO,TELEFONO) values (1,'123456','Gandalf','Gabriel','Monge','gabriel.monge.lizano@gmail.com','86837078');
--------------------------------------------------------
--  DDL for Index BEBIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."BEBIDA_PK" ON "VSCODE"."BEBIDA" ("ID_BEBIDA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."EMPLEADO_PK" ON "VSCODE"."EMPLEADO" ("ID_EMPLEADO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLATILLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."PLATILLO_PK" ON "VSCODE"."PLATILLO" ("ID_PLATILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."RESTAURANTE_PK" ON "VSCODE"."RESTAURANTE" ("ID_RESTAURANTE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."REVIEW_PK" ON "VSCODE"."REVIEW" ("ID_REVIEW")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."USER_PK" ON "VSCODE"."USUARIO" ("ID_USER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BEBIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."BEBIDA_PK" ON "VSCODE"."BEBIDA" ("ID_BEBIDA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."EMPLEADO_PK" ON "VSCODE"."EMPLEADO" ("ID_EMPLEADO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLATILLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."PLATILLO_PK" ON "VSCODE"."PLATILLO" ("ID_PLATILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."RESTAURANTE_PK" ON "VSCODE"."RESTAURANTE" ("ID_RESTAURANTE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."REVIEW_PK" ON "VSCODE"."REVIEW" ("ID_REVIEW")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VSCODE"."USER_PK" ON "VSCODE"."USUARIO" ("ID_USER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VSCODE"."TRIGGER_EMPLEADO"
    BEFORE INSERT ON empleado
    FOR EACH ROW
  BEGIN
    :new.id_Empleado := empleado_seq.nextval;
  END;
/
ALTER TRIGGER "VSCODE"."TRIGGER_EMPLEADO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_RESTAURANTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VSCODE"."TRIGGER_RESTAURANTE"
    BEFORE INSERT ON restaurante
    FOR EACH ROW
  BEGIN
    :new.id_restaurante := restaurante_seq.nextval;
  END;
/
ALTER TRIGGER "VSCODE"."TRIGGER_RESTAURANTE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VSCODE"."TRIGGER_USUARIO"
    BEFORE INSERT ON usuario
    FOR EACH ROW
  BEGIN
    :new.id_User := usuario_seq.nextval;
  END;
/
ALTER TRIGGER "VSCODE"."TRIGGER_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VSCODE"."TRIGGER_EMPLEADO"
    BEFORE INSERT ON empleado
    FOR EACH ROW
  BEGIN
    :new.id_Empleado := empleado_seq.nextval;
  END;
/
ALTER TRIGGER "VSCODE"."TRIGGER_EMPLEADO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_RESTAURANTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VSCODE"."TRIGGER_RESTAURANTE"
    BEFORE INSERT ON restaurante
    FOR EACH ROW
  BEGIN
    :new.id_restaurante := restaurante_seq.nextval;
  END;
/
ALTER TRIGGER "VSCODE"."TRIGGER_RESTAURANTE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VSCODE"."TRIGGER_USUARIO"
    BEFORE INSERT ON usuario
    FOR EACH ROW
  BEGIN
    :new.id_User := usuario_seq.nextval;
  END;
/
ALTER TRIGGER "VSCODE"."TRIGGER_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADDUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."ADDUSER" (
    in_nombre IN usuario.nombre%TYPE,
    in_userPassword IN usuario.userPassword%TYPE,
    in_userName IN usuario.userName%TYPE,
    in_apellido IN usuario.apellido%TYPE,
    in_correo IN usuario.correo%TYPE,
    in_telefono IN usuario.telefono%TYPE)
IS
BEGIN
    INSERT INTO usuario (nombre, userName, userPassword, apellido, correo, telefono)
    VALUES (in_nombre, in_userName, in_userPassword, in_apellido, in_correo, in_telefono);
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ALTERUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."ALTERUSER" (
    ind_userName IN usuario.userName%TYPE,
    ind_userPassword IN usuario.userPassword%TYPE,
    in_userName IN usuario.userName%TYPE,
    in_nombre IN usuario.nombre%TYPE,
    in_userPassword IN usuario.userPassword%TYPE,
    in_apellido IN usuario.apellido%TYPE,
    in_correo IN usuario.correo%TYPE,
    in_telefono IN usuario.telefono%TYPE)
IS
BEGIN
    DBMS_OUTPUT.PUT_LINE(ind_userName||' '||ind_userPassword);
    UPDATE USUARIO SET
        username = in_userName,
        userpassword = in_userPassword,
        nombre = in_nombre,
        apellido = in_apellido,
        correo = in_correo,
        telefono = in_telefono
    WHERE userName = ind_userName AND userpassword = ind_userPassword;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETEUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."DELETEUSER" (
    p_userName in usuario.userName%TYPE,
    p_userPassword IN usuario.userPassword%TYPE)
IS
Begin
    Delete from USUARIO WHERE userName = p_userName and userPassword = p_userPassword ;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure EDITREVIEW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."EDITREVIEW" (
    in_idRev IN review.id_Review%TYPE,
    in_rating IN review.rest_score%TYPE,
    in_review IN review.review%TYPE,
    in_edited IN review.edited%TYPE)
IS
BEGIN
    UPDATE REVIEW SET
        rest_score = in_rating,
        review = in_review,
        edited = in_edited
    WHERE id_Review = in_idRev;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Review edited');

END;

/
--------------------------------------------------------
--  DDL for Procedure GETUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."GETUSER" (
    in_nombre IN usuario.nombre%TYPE,
    in_apellido IN usuario.apellido%TYPE)
IS
    out_id usuario.id_User%TYPE;
    out_nombre usuario.nombre%TYPE;
    out_apellido usuario.apellido%TYPE;
    out_correo usuario.correo%TYPE;
    out_telefono usuario.telefono%TYPE;
BEGIN
    SELECT
        id_User, NOMBRE, APELLIDO, CORREO, TELEFONO
    INTO
        out_id, out_nombre, out_apellido, out_correo, out_telefono
    FROM usuario
    WHERE nombre = in_nombre
        AND apellido = in_apellido;

    DBMS_OUTPUT.PUT_LINE(out_id ||','|| out_nombre ||','|| out_apellido ||','|| out_correo ||', '|| out_telefono);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTREVIEW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."INSERTREVIEW" (
    in_restaurante IN review.restaurante%TYPE,
    in_usuario IN review.usuario%TYPE,
    in_rating IN review.rest_score%TYPE,
    in_review IN review.review%TYPE,
    in_created IN review.created%TYPE,
    in_ubicacion IN review.ubicacion%TYPE,
    in_fileName IN review.fileName%TYPE)
IS
BEGIN
    INSERT INTO review (restaurante, usuario, rest_score, review, created, ubicacion, fileName)
    VALUES (in_restaurante, in_usuario, in_rating, in_review, in_created, in_ubicacion, in_fileName);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Review created');
END;

/
--------------------------------------------------------
--  DDL for Procedure PROC1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."PROC1" ()
BEGIN
  CALL DBMS_OUTPUT.PUT_LINE( 'PROC1 put this line in the message buffer.' );
END@

/
--------------------------------------------------------
--  DDL for Procedure PROC2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "VSCODE"."PROC2" ()
BEGIN
  CALL DBMS_OUTPUT.PUT_LINE( 'PROC2 put this line in the message buffer.' );
END;

/
--------------------------------------------------------
--  DDL for Package RESTAURANTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "VSCODE"."RESTAURANTES"
      as
        g_restaurante restaurante.id_restaurante%type;

        function get_restaurante
          return restaurante.id_restaurante%type;

        procedure set_restaurante( p_restaurante in restaurante.id_restaurante%type );
      end restaurantes;

/
--------------------------------------------------------
--  DDL for Package Body RESTAURANTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "VSCODE"."RESTAURANTE"
      as
        procedure set_restaurante( p_restaurante in restaurante.id_restaurante%type )
        as
        begin
          g_restaurante := p_restaurante;
        end;

        function get_restaurante
          return restaurante.id_restaurante%type
        is
        begin
          return g_restaurante;
        end;
      end;

/
--------------------------------------------------------
--  DDL for Package Body RESTAURANTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "VSCODE"."RESTAURANTES"
      as
        procedure set_restaurante( p_restaurante in restaurante.id_restaurante%type )
        as
        begin
          g_restaurante := p_restaurante;
        end;

        function get_restaurante
          return restaurante.id_restaurante%type
        is
        begin
          return g_restaurante;
        end;
      end;

/
--------------------------------------------------------
--  DDL for Function RESTAURANTESELECT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "VSCODE"."RESTAURANTESELECT" (selector_In in number)
       return VARCHAR2
       IS
           restaurante varchar2(500) := '';
           tipo varchar2(500) := '';
           rango varchar2(500) := '';
           mensaje varchar2(500) := '';
       BEGIN
           RESTAURANTES.SET_RESTAURANTE(3);
           select nombre, tipo_comida, price_range into restaurante, tipo, rango from RESTAURANTE_VIEW;
           mensaje := ('Restaurante: ' || restaurante || ' | Tipo: ' || tipo || ' | Rango de Precio: ' || rango);
           return mensaje;
       end;

/
--------------------------------------------------------
--  Constraints for Table BEBIDA
--------------------------------------------------------

  ALTER TABLE "VSCODE"."BEBIDA" MODIFY ("ID_BEBIDA" NOT NULL ENABLE);
  ALTER TABLE "VSCODE"."BEBIDA" ADD CONSTRAINT "BEBIDA_PK" PRIMARY KEY ("ID_BEBIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "VSCODE"."EMPLEADO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "VSCODE"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLATILLO
--------------------------------------------------------

  ALTER TABLE "VSCODE"."PLATILLO" MODIFY ("ID_PLATILLO" NOT NULL ENABLE);
  ALTER TABLE "VSCODE"."PLATILLO" ADD CONSTRAINT "PLATILLO_PK" PRIMARY KEY ("ID_PLATILLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "VSCODE"."RESTAURANTE" MODIFY ("ID_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "VSCODE"."RESTAURANTE" ADD CONSTRAINT "RESTAURANTE_PK" PRIMARY KEY ("ID_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "VSCODE"."REVIEW" MODIFY ("ID_REVIEW" NOT NULL ENABLE);
  ALTER TABLE "VSCODE"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("ID_REVIEW")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "VSCODE"."USUARIO" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "VSCODE"."USUARIO" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BEBIDA
--------------------------------------------------------

  ALTER TABLE "VSCODE"."BEBIDA" ADD CONSTRAINT "FK_BEBIDA" FOREIGN KEY ("RESTAURANTE")
	  REFERENCES "VSCODE"."RESTAURANTE" ("ID_RESTAURANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIETA
--------------------------------------------------------

  ALTER TABLE "VSCODE"."DIETA" ADD CONSTRAINT "FK_DIETA" FOREIGN KEY ("RESTAURANTE")
	  REFERENCES "VSCODE"."RESTAURANTE" ("ID_RESTAURANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "VSCODE"."EMPLEADO" ADD CONSTRAINT "FK_EMPLEADO" FOREIGN KEY ("RESTAURANTE")
	  REFERENCES "VSCODE"."RESTAURANTE" ("ID_RESTAURANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLATILLO
--------------------------------------------------------

  ALTER TABLE "VSCODE"."PLATILLO" ADD CONSTRAINT "FK_PLATILLO" FOREIGN KEY ("RESTAURANTE")
	  REFERENCES "VSCODE"."RESTAURANTE" ("ID_RESTAURANTE") ENABLE;
